### PR TITLE
Fixes panic in security plugin when token not present in request

### LINKED ISSUE #39: Security plugin panics when token is not provided
When we define security DSL In the design and Define Token in the payload and mark token as not required the generated code panics with `runtime error: invalid memory address or nil pointer dereference`
Ex:
```
Method("Example", func() {
		Security(JWTAuth, func() {
			Scope("gaps:write")
		})

		Payload(func() {
			Token("token", String, "JWT token used to perform authorization")
			Attribute("Id", UInt, "ID identifies a resource by ID.")
			
			Required("Id")
		})
	})
```

### PR DESCRIPTION
**Pull request by nitinmohan87**
Fixes #39

### CODE REVIEW

File: security/generate.go [hunk 1]
```diff
@@ -311,23 +312,7 @@ const dummyAuthFuncsT = `{{ range $sd := . }}
...
-	if key == "" {
-		return ctx, &{{ $sd.ServicePkg }}.Unauthorized{"invalid key"}
-	}
-	{{- else }}
-	if token == "" {
-		return ctx, &{{ $sd.ServicePkg }}.Unauthorized{"invalid token"}
-	}
-	{{- end }}
-	return ctx, nil
+	return ctx, fmt.Errorf("internal error")
```
Comment (raphael) [inline security/generate.go]: how about we use "not implemented" instead?

**Comment by raphael** [comment]
Thank you!
